
package edu.cibertec.jaad.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicTimeServiceService", targetNamespace = "http://ws.jaad.cibertec.edu/", wsdlLocation = "http://localhost:9876/timeService?wsdl")
@HandlerChain(file="handler-chain.xml")
public class BasicTimeServiceService
    extends Service
{

    private final static URL BASICTIMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICTIMESERVICESERVICE_EXCEPTION;
    private final static QName BASICTIMESERVICESERVICE_QNAME = new QName("http://ws.jaad.cibertec.edu/", "BasicTimeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/timeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICTIMESERVICESERVICE_WSDL_LOCATION = url;
        BASICTIMESERVICESERVICE_EXCEPTION = e;
    }

    public BasicTimeServiceService() {
        super(__getWsdlLocation(), BASICTIMESERVICESERVICE_QNAME);
    }

    public BasicTimeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICTIMESERVICESERVICE_QNAME, features);
    }

    public BasicTimeServiceService(URL wsdlLocation) {
        super(wsdlLocation, BASICTIMESERVICESERVICE_QNAME);
    }

    public BasicTimeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICTIMESERVICESERVICE_QNAME, features);
    }

    public BasicTimeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicTimeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "BasicTimeServicePort")
    public TimeService getBasicTimeServicePort() {
        return super.getPort(new QName("http://ws.jaad.cibertec.edu/", "BasicTimeServicePort"), TimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "BasicTimeServicePort")
    public TimeService getBasicTimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jaad.cibertec.edu/", "BasicTimeServicePort"), TimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICTIMESERVICESERVICE_EXCEPTION!= null) {
            throw BASICTIMESERVICESERVICE_EXCEPTION;
        }
        return BASICTIMESERVICESERVICE_WSDL_LOCATION;
    }

}
