
package edu.cibertec.jaad.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlumnoService", targetNamespace = "http://ws.jaad.cibertec.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlumnoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.cibertec.jaad.ws.Alumno
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://ws.jaad.cibertec.edu/", className = "edu.cibertec.jaad.ws.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://ws.jaad.cibertec.edu/", className = "edu.cibertec.jaad.ws.RetrieveResponse")
    public Alumno retrieve(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAlumno", targetNamespace = "http://ws.jaad.cibertec.edu/", className = "edu.cibertec.jaad.ws.AddAlumno")
    @ResponseWrapper(localName = "addAlumnoResponse", targetNamespace = "http://ws.jaad.cibertec.edu/", className = "edu.cibertec.jaad.ws.AddAlumnoResponse")
    public boolean addAlumno(
        @WebParam(name = "arg0", targetNamespace = "")
        Alumno arg0);

}
