
package com.cesar.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SibTrabajadorService", targetNamespace = "http://ws.cesar.com/", wsdlLocation = "file:/D:/Cibertec/JAAD-2015-III/05_WKs/wkm01/ClienteSoap02Trabajador/src/main/resources/SibTrabajadorService.wsdl")
public class SibTrabajadorService
    extends Service
{

    private final static URL SIBTRABAJADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIBTRABAJADORSERVICE_EXCEPTION;
    private final static QName SIBTRABAJADORSERVICE_QNAME = new QName("http://ws.cesar.com/", "SibTrabajadorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Cibertec/JAAD-2015-III/05_WKs/wkm01/ClienteSoap02Trabajador/src/main/resources/SibTrabajadorService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIBTRABAJADORSERVICE_WSDL_LOCATION = url;
        SIBTRABAJADORSERVICE_EXCEPTION = e;
    }

    public SibTrabajadorService() {
        super(__getWsdlLocation(), SIBTRABAJADORSERVICE_QNAME);
    }

    public SibTrabajadorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TrabajadorService
     */
    @WebEndpoint(name = "SibTrabajadorPort")
    public TrabajadorService getSibTrabajadorPort() {
        return super.getPort(new QName("http://ws.cesar.com/", "SibTrabajadorPort"), TrabajadorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrabajadorService
     */
    @WebEndpoint(name = "SibTrabajadorPort")
    public TrabajadorService getSibTrabajadorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cesar.com/", "SibTrabajadorPort"), TrabajadorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIBTRABAJADORSERVICE_EXCEPTION!= null) {
            throw SIBTRABAJADORSERVICE_EXCEPTION;
        }
        return SIBTRABAJADORSERVICE_WSDL_LOCATION;
    }

}
