
package com.cesar.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TrabajadorService", targetNamespace = "http://ws.cesar.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrabajadorService {


    /**
     * 
     * @return
     *     returns java.util.List<com.cesar.ws.Trabajador>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTodo", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.ListarTodo")
    @ResponseWrapper(localName = "listarTodoResponse", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.ListarTodoResponse")
    public List<Trabajador> listarTodo();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cesar.ws.Trabajador
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarTrabajador", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.EncontrarTrabajador")
    @ResponseWrapper(localName = "encontrarTrabajadorResponse", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.EncontrarTrabajadorResponse")
    public Trabajador encontrarTrabajador(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearTrabajador", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.CrearTrabajador")
    @ResponseWrapper(localName = "crearTrabajadorResponse", targetNamespace = "http://ws.cesar.com/", className = "com.cesar.ws.CrearTrabajadorResponse")
    public String crearTrabajador(
        @WebParam(name = "arg0", targetNamespace = "")
        Trabajador arg0);

}
