
package com.futbol.cesar.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FutbolistaSibService", targetNamespace = "http://service.cesar.futbol.com/", wsdlLocation = "file:/D:/Cibertec/JAAD-2015-III/05_WKs/wkm01/ClienteSoapFutbolista/src/main/resources/FutbolistaSibService.wsdl")
public class FutbolistaSibService
    extends Service
{

    private final static URL FUTBOLISTASIBSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUTBOLISTASIBSERVICE_EXCEPTION;
    private final static QName FUTBOLISTASIBSERVICE_QNAME = new QName("http://service.cesar.futbol.com/", "FutbolistaSibService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Cibertec/JAAD-2015-III/05_WKs/wkm01/ClienteSoapFutbolista/src/main/resources/FutbolistaSibService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUTBOLISTASIBSERVICE_WSDL_LOCATION = url;
        FUTBOLISTASIBSERVICE_EXCEPTION = e;
    }

    public FutbolistaSibService() {
        super(__getWsdlLocation(), FUTBOLISTASIBSERVICE_QNAME);
    }

    public FutbolistaSibService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns FutbolistaSei
     */
    @WebEndpoint(name = "FutbolistaSibPort")
    public FutbolistaSei getFutbolistaSibPort() {
        return super.getPort(new QName("http://service.cesar.futbol.com/", "FutbolistaSibPort"), FutbolistaSei.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FutbolistaSei
     */
    @WebEndpoint(name = "FutbolistaSibPort")
    public FutbolistaSei getFutbolistaSibPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cesar.futbol.com/", "FutbolistaSibPort"), FutbolistaSei.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUTBOLISTASIBSERVICE_EXCEPTION!= null) {
            throw FUTBOLISTASIBSERVICE_EXCEPTION;
        }
        return FUTBOLISTASIBSERVICE_WSDL_LOCATION;
    }

}
